### ISSUE TITLE
You must use Bundler 2 or greater with this lockfile.

### ISSUE THREAD

**Issue by Axxon** [BretFisher/jekyll-serve#19]
Hello i just start to try running Jekyll with this repo and i got:
```
docker run -p 8080:4000 -v $(pwd):/site bretfisher/jekyll-serve
You must use Bundler 2 or greater with this lockfile.
```
Please what's wrong ?

**Comment by BretFisher** [comment]
This repo only had bundler 1.x installed. I've added 2.x as well so that image on docker hub should be updated later today for you to do a `pull` and try again. You can reopen this issue after tomorrow if it's still an issue (but remember you need to pull or delete the local image from the cache to ensure you get the latest)

**Comment by Axxon** [comment]
Thanks you very much for your reactivity.
