### ISSUE TITLE
is there a way to change to port from 4000

### ISSUE THREAD

**Issue by jmjamison** [BretFisher/jekyll-serve#77]
Is there a way to change from port 4000 to 4001 or something else?   I've tried changing the command line command but it seems to ignore what I put in.   Thanks.

**Comment by jmjamison** [comment]
Apologies.   I should have added I'm running this  windows 10, WSL2.

**Comment by BretFisher** [comment]
When using docker, you don't need to change the port Jekyll is running on inside the container, because each container gets its own private IP inside docker networks. If you wanted it to run on localhost:8080 (for example, in Docker Desktop + WSL2), then you would run:

`docker run -p 8080:4000 -v $(pwd):/site bretfisher/jekyll-serve`

Does that help?
